### ISSUE TITLE
Getting The Projection Matrix from Q

### ISSUE THREAD

**Issue by Hickles02** [Hickles02/FYP478#17]
Hi Sir,

I'm struggling to compute the projection matrix using this equation:
![image](https://user-images.githubusercontent.com/63748071/180270545-0e35fbc0-6c1c-4cd2-ad7a-3faf3930df81.png)

This is the Q I get from the example they use in Chapter 3:
![image](https://user-images.githubusercontent.com/63748071/180271013-892251d5-c4b5-4723-82de-33164790cc00.png)

And here are the rest of my variables:
[0 I]:
![image](https://user-images.githubusercontent.com/63748071/180272290-45a62db5-c81a-4ca0-8ecf-03647a5c98f5.png)
[R1; 0]
![image](https://user-images.githubusercontent.com/63748071/180271219-5df520ae-a5d4-4b36-9cac-1b621529aeee.png)
Permutation Matrix
![image](https://user-images.githubusercontent.com/63748071/180272372-caadfbab-6486-407b-a0a9-b430ffb12bcb.png)

Then I'm solving Qx2 as follows:
![image](https://user-images.githubusercontent.com/63748071/180272733-97ee53da-5183-4197-9a21-315bcd274ead.png)

[0 I] is a 4 x 5 matrix whilst [R1; 0] is a 4 x 3 matrix, so I don't understand how the equation works.

Thanks for the help.

**Comment by tmlouw** [comment]
Sorry for the late reply. I wrote the following code and got the exact same answer as the textbook (example 3-1):

```
%%
clc
clear
clf

Ax = [1 0; 0 0; 0 0; 0 -1];
Au = [-1 -1 0 0; 1 0 -1 0; 0 1 0 -1; 0 0 1 1];

[Q,R] = qr(Au)
s = 3;
Q1 = Q(:, 1:s);
Q2 = Q(:, s+1:end);
R1 = R(1:s, 1:s);
R2 = R(1:s, s+1:end);
P = Q2';
```

**Comment by Hickles02** [comment]
Awesome. Thanks so much @tmlouw.
