### ISSUE TITLE
R1 & R2 from R

### ISSUE THREAD

**Issue by Hickles02** [Hickles02/FYP478#18]
Hi Sir, 

Getting R1 from R is fine, but the textbook says that R2 is then an s x (p-s) matrix. 
From the example, there are 4 unmeasured variables, so p = 4. Then from R, you can see s = 3 because the upper triangle is a 3 x 3 matrix. 
So with this information, this is how I get R1 & R2
R = 
![image](https://user-images.githubusercontent.com/63748071/180273626-e082a15a-6405-409b-83e9-2d23328f354b.png)
R1 = 
![image](https://user-images.githubusercontent.com/63748071/180273730-17a5d90a-080e-496c-98bd-c42eb1bcf8fc.png)
R2 =
![image](https://user-images.githubusercontent.com/63748071/180273782-0ae9781e-f012-4c04-ba0c-199947d11300.png)

Then, to test for observability, I use the following equation:
![image](https://user-images.githubusercontent.com/63748071/180273950-76591afe-f939-437d-baf3-af658730bb15.png)

This is my answer:
![image](https://user-images.githubusercontent.com/63748071/180274111-4857f096-9bd6-48ed-826f-73d608d0f5b4.png)

This is the textbook's answer for the same example:
![image](https://user-images.githubusercontent.com/63748071/180274208-d019dfbb-a023-4291-949b-4e28240bff5b.png)

So my question is then if I'm calculating R1 & R2 correctly?

Thanks Professor.

**Comment by tmlouw** [comment]
I get a different R matrix when I use the QR factorisation. Check the code I provided in the other issue
