### ISSUE TITLE
Incorrect calculation of specificity / sensitivity.

### ISSUE THREAD

**Issue by tmlouw** [Hickles02/FYP478#29]
https://github.com/Hickles02/FYP478/blob/0e36b582264cecd1b90548268db73c4ab1b9595f/MATLAB/GED.m#L71

@Hickles02 Please check https://en.wikipedia.org/wiki/Sensitivity_and_specificity, you are calculating sensitivity and specificity incorrectly. 

The way your code is written:
- sum(H0) = number of true negatives [alarm didn't go off, no fault present] = TN
- sum(Type2) = number of false negatives [alarm didn't go off, but there is a fault] = FN
- sum(H1) = number of true positives [alarm did go off, fault is present] = TP
- sum(Type1) = number of false positives [alarm did go off, no fault present] = FP

You are calculating sensitivity = sum(H1) / 1001 = TP / (TN+FN+TP+FP). The correct equation for sensitivity is TP / (TP+FN), which is the fraction of the time the alarm goes off **in the presence of a fault**. Similarly, you are calculating specificity = TN / (TN+FN+TP+FP), but the correct equation is TN / (TN + FP), which is the fraction of time the alarm is off **when no fault is present**. 

Fixing this will significantly improve your sensitivity and specificity

**Comment by Hickles02** [comment]
Awesome, this makes a lot more sense. Thanks @tmlouw
