### ISSUE TITLE
Clear Type1, Type2, H0 and H1 variables

### ISSUE THREAD

**Issue by tmlouw** [Hickles02/FYP478#30]
https://github.com/Hickles02/FYP478/blob/0e36b582264cecd1b90548268db73c4ab1b9595f/MATLAB/GED.m#L46

Make sure to set Type1, Type2, H0 and H1 equal to zero every time you start with a new value for "alpha" (in other words, just before the for-loop). Essentially, you aren't "clearing" the results from the previous run.

**Comment by Hickles02** [comment]
Great stuff, now it's working. Thanks @tmlouw
