### ISSUE TITLE
Intermediaries - Calculation of v.L

### ISSUE THREAD

**Issue by Hickles02** [Hickles02/FYP478#4]
![image](https://user-images.githubusercontent.com/63748071/168976916-3f38f746-d75d-4fb3-9cb0-c19ec6dd6229.png)

v.L should actually be [5993x4 double]. The problem is coming from the fact that my dependent variable is specified as [10x1].

**Comment by tmlouw** [comment]
@Hickles02 Was this issue resolved?

**Comment by Hickles02** [comment]
@tmlouw No this hasn't been resolved. I think this is also the reason why my mol fractions aren't correct (the one is above one & the other is zero, see the below image).
![image](https://user-images.githubusercontent.com/63748071/169703552-52ac09c3-c569-4408-a14d-d5b29512eb43.png)
 
I've doubled checked all my equations. Obviously it could still be the parameters that I haven't added, but I think this is the issue.

**Comment by Hickles02** [comment]
@tmlouw Hi Professor.
Would you please take a screenshot of what you changed in my code this morning? I remember it wasn't that much. 
I'm struggling to get it right, so thought just want to see what you did again. 
Thanks.

**Comment by Hickles02** [comment]
@tmlouw Hi Professor.
![image](https://user-images.githubusercontent.com/63748071/170436978-d022dab5-6c97-43dc-9032-94eac03625a0.png)
Everything is now as it should be. The only problem I've got left is my liquid mol fraction that is being calculated is still above one.
![image](https://user-images.githubusercontent.com/63748071/170437142-496fb5bd-2f87-4d6b-bab6-d7cf1a711991.png)
I've updated my code in Github, with the updated naming. So if you would please have a look and let me know if you spot something that's not right.  Thanks for all the help.
