### ISSUE TITLE
Initial Conditions

### ISSUE THREAD

**Issue by Hickles02** [Hickles02/FYP478#6]
https://github.com/Hickles02/FYP478/blob/77396aace18d3152b7a4fe47f8b567958ceb13d6/MATLAB/main_system.m#L33-L35

@tmlouw 
Marlin specifies the initial molar holdup on each tray as one but says nothing regarding the mole fractions. Do you agree that they should all be 0?

**Comment by tmlouw** [comment]
I would rather set them equal to 0.5 initially. Funny things can happen close to zero...
