### ISSUE TITLE
Variable naming

### ISSUE THREAD

**Issue by tmlouw** [Hickles02/FYP478#8]
@Hickles02 
https://github.com/Hickles02/FYP478/blob/a8602db12ab3d42400b8d11ba9b025b0a76e91a4/MATLAB/simulate_ODEs.m#L5

It's important to write code that is readable. Why are you naming both your molar hold-up and your mol fraction as "MM"?

Rather let:
MM = x(1:p.N);
X = x(p.N+1 : end);

**Comment by Hickles02** [comment]
I tried doing it that way but the code wasn't running. But I'll give it a go again.

**Comment by tmlouw** [comment]
Please fix it. It's very difficult to read + debug your code with the strange variable naming you have in place now.

**Comment by Hickles02** [comment]
@tmlouw Just updated the code with the new naming.
